---

- name: dynamic_inventory/esxifree | Get existing VMware instance info
  vmware_vm_info:
    username: "{{ cluster_vars.username }}"
    password: "{{ cluster_vars.password }}"
    hostname: "{{ cluster_vars.esxi_ip }}"
    validate_certs: no
  register: r__vmware_vm_info
  delegate_to: localhost
  run_once: true

- name: dynamic_inventory/esxifree | Get existing VMware instance facts
  vmware_guest_info:
    username: "{{ cluster_vars.username }}"
    password: "{{ cluster_vars.password }}"
    hostname: "{{ cluster_vars.esxi_ip }}"
    validate_certs: no
    datacenter: None
    uuid: "{{item.uuid}}"
  with_items: "{{ r__vmware_vm_info.virtual_machines | to_json | from_json | json_query(\"[?starts_with(guest_name, '\"+cluster_name+\"') && power_state=='poweredOn']\") }}"
  register: r__vmware_guest_info
  delegate_to: localhost
  run_once: true

## esxifree hosts must use the esxi 'annotations' field as json.  They are stored as unconventional text in the vmx file, so must
## be converted into inline-json within the facts.  If the annotation field is not convertible to json, then we don't consider this VM part of the cluster.
- name: dynamic_inventory/esxifree | Update r__vmware_guest_info result with json-parsed annotations
  set_fact:
    r__vmware_guest_info: |
      {% set res = {'results': []} -%}
        {%- for result in r__vmware_guest_info.results -%}
          {%- set loadloose_res = result.instance.annotation | json_loads_loose -%}
          {%- if loadloose_res | type_debug == 'dict' or loadloose_res | type_debug == 'list' -%}
            {%- set _ = result.instance.update({'annotation': loadloose_res}) -%}
            {%- set _ = res.results.append(result) -%}
          {%- endif -%}
        {%- endfor -%}
      {{ res }}

#- debug: msg={{r__vmware_guest_info}}

- name: dynamic_inventory/esxifree | Set dynamic_inventory_flat
  set_fact:
    dynamic_inventory_flat: "{{ r__vmware_guest_info.results | json_query(\"[].{hosttype: instance.annotation.hosttype, hostname: item.guest_name, private_ip: item.ip_address, inventory_ip: item.ip_address}\") | default([]) }}"
