---

- include_tasks: aws.yml
  when: cluster_vars.type == "aws"

- include_tasks: gce.yml
  when: cluster_vars.type == "gce"


- assert: { that: "dynamic_inventory_flat is defined", msg: "dynamic_inventory_flat is not defined" }

- debug: msg="{{dynamic_inventory_flat}}"

- name: Wait for port 22 to become open and contain "OpenSSH".
  wait_for:
    port: 22
    host: "{{ item.inventory_ip }}"
    search_regex: OpenSSH
    delay: 1
  with_items: "{{ dynamic_inventory_flat }}"
  connection: local

- name: Add hosts to dynamic inventory
  add_host:
    name: "{{ item.hostname }}"
    groups: ["{{ item.hosttype }}","{{ cluster_name }}","{{ clusterid }}"]
    ansible_host: "{{ item.inventory_ip }}"
    hosttype: "{{ item.hosttype }}"
  with_items: "{{ dynamic_inventory_flat }}"


- stat: path={{inventory_file}}
  register: stat_inventory_file
  when: inventory_file is defined

- set_fact:
    new_inventory_file: "{{ inventory_file if (((stat_inventory_file.stat is defined and stat_inventory_file.stat.exists) or (stat_inventory_file.skipped is defined and stat_inventory_file.skipped)) and inventory_dir is defined and inventory_dir==playbook_dir) else playbook_dir + '/inventory_' + cluster_name }}"

- name: Populate inventory file from dynamic inventory
  copy:
    content: |
      {% for groupname in groups.keys() -%}
      {% if groupname not in ["all", "ungrouped"] -%}
      [{{ groupname }}]
      {% for hostname in groups[groupname] %}
      {{ hostname }} ansible_host={{hostvars[hostname].ansible_host}} hosttype={{ hostvars[hostname].hosttype }}
      {% endfor %}

      {% endif %}
      {% endfor %}
    dest: "{{new_inventory_file}}"
    force: yes
