---

- debug: msg="Stop {{host_to_stop.hostname}}, release {{release_to_stop}}"

- name: gcp_gather | Get GCP instance facts
  gcp_compute_instance_info:
    zone: "{{cluster_vars.region}}-{{cluster_hosts_target  | json_query('[? hostname == `' + host_to_stop.hostname + '`].az_name|[0]')}}"
    filters:
      - "name = {{host_to_stop.hostname}}*"
      - "status = RUNNING"
    project: "{{cluster_vars.project_id}}"
    auth_kind: "serviceaccount"
    service_account_file: "{{gcp_credentials_file}}"
    scopes: ["https://www.googleapis.com/auth/compute.readonly"]
  register: gcp_compute_instance_info
  delegate_to: localhost
  run_once: true

- name: "set argument variables for {{mainclusteryml}}"
  set_fact:
    instance_to_create: "{{ gcp_compute_instance_info | json_query('resources[0].name') | regex_replace('-(?!.*-).*') + '-'+cluster_suffix}}"
