---

- name: "Get A record for {{fqdn}}"
  infoblox:
    server: "{{ infoblox.server }}"
    username: "{{ infoblox.username }}"
    password: "{{ infoblox.password }}"
    api_version: 2.6.1
    action: get_a_record
    name: "{{ fqdn }}"
  register: get_a_record
  delegate_to: localhost
  run_once: true
  become: false

- name: "Create A record for {{fqdn}} ({{ip}})"
  infoblox:
    server: "{{ infoblox.server }}"
    username: "{{ infoblox.username }}"
    password: "{{ infoblox.password }}"
    api_version: 2.6.1
    action: create_a_record
    name: "{{ fqdn }}"
    address: "{{ip}}"
    ttl: 60
  register: create_a_record
  when: get_a_record.msg is defined and "No A record for name" in get_a_record.msg
  delegate_to: localhost
  run_once: true
  become: false

- name: "Update A record for {{fqdn}} ({{ip}})"
  infoblox:
    server: "{{ infoblox.server }}"
    username: "{{ infoblox.username }}"
    password: "{{ infoblox.password }}"
    api_version: 2.6.1
    action: update_a_record
    name: "{{ fqdn }}"
    address: "{{ip}}"
    current:
      name: "{{ fqdn }}"
      address: "{{get_a_record.result[0].ipv4addr}}"
    ttl: 60
  register: update_a_record
  when: get_a_record.result is defined and "Object managed by ansible-infoblox module" in get_a_record.result[0].comment
  delegate_to: localhost
  run_once: true
  become: false
