---

- name: Disable requiretty in sudoers to enable pipelining
  become: yes
  lineinfile:
    dest: /etc/sudoers
    regexp: '(^Defaults requiretty)$'
    line: '#\1",'
    backrefs: yes
  vars:
    ansible_ssh_pipelining: no

- name: Add hostname to hosts (gives hostname resolution without calling out to DNS.  Needed on Ubuntu.)
  become: yes
  lineinfile:
    path: /etc/hosts
    regexp: '^{{ansible_default_ipv4.address}}'
    line: '{{ansible_default_ipv4.address}} {{inventory_hostname}}.{{cluster_vars.dns_zone_external}} {{inventory_hostname}}'
#    regexp: '^127\.0\.1\.1'
#    line: '127.0.1.1 {{inventory_hostname}}'
    insertbefore: "BOF"

- name: Create /var/log/journal
  become: true
  file:
    path: "/var/log/journal"
    state: directory
    mode: 0755
  when: (static_journal is defined and static_journal|bool)

- name: Attach auto_volumes
  include_tasks: disks_auto.yml

- name: install prometheus node exporter daemon
  include_tasks: prometheus_node_exporter.yml
  when: (prometheus_node_exporter_install is defined and prometheus_node_exporter_install|bool)

- name: Install elastic filebeat
  include_tasks: filebeat.yml
  when: (filebeat_install is defined and filebeat_install|bool)

- name: Install security cloud agent
  include_tasks: cloud_agents.yml
  when: (cloud_agent is defined and cloud_agent)

- name: Update packages (unless skip_package_upgrade is defined)
  include_tasks: pkgupdate.yml
  when: (skip_package_upgrade is not defined) or (skip_package_upgrade is defined and not skip_package_upgrade|bool)

- name: Set hostname (e.g. AWS doesn't set it automatically)
  become: true
  hostname:
    name: "{{inventory_hostname.split('.')[0]}}"

# Openstack
- block:
    - name: set preserve_hostname in cloud.cfg
      lineinfile:
        path: /etc/cloud/cloud.cfg
        line: 'preserve_hostname: true'
        insertbefore: '^cloud_init_modules:'
      become: true

    - name: remove domain info from hostname
      lineinfile:
        path: /etc/hostname
        regexp: '^(.*?)\..*'
        line: '\1'
        backrefs: yes
      become: true

    - name: Apply openstack DNS (if dns_server=openstack and dns.tld_external is set)
      include_tasks: dns_openstack_create_update_a.yml
      vars:
        - fqdn: "{{outer_item.hostname}}.{{cluster_vars.dns_zone_external}}"
        - ip: "{{ hostvars[outer_item.hostname]['ansible_host'] }}"
      with_items: "{{ cluster_hosts_flat }}"
      loop_control:
        loop_var: outer_item
      when: cluster_vars.dns_server == "openstack" and cluster_vars.dns_zone_external is defined and cluster_vars.dns_zone_external != ""
  when: cluster_vars.type == "openstack"


- name: Create/ Update DNS A records in Infoblox (if applicable)
  infoblox:
    server: "{{ infoblox[buildenv].server }}"
    username: "{{ infoblox[buildenv].username }}"
    password: "{{ infoblox[buildenv].password }}"
    action: set_a_record
    name: "{{item.hostname}}.{{cluster_vars.dns_zone_external}}"
    address: "{{ hostvars[item.hostname]['ansible_host'] }}"
    ttl: 60
  become: false
  delegate_to: localhost
  run_once: true
  with_items: "{{ cluster_hosts_flat }}"
  when: (cluster_vars.dns_server is defined and cluster_vars.dns_server != "") and cluster_vars.dns_server=="infoblox" and (cluster_vars.dns_zone_external is defined and cluster_vars.dns_zone_external != "")

## Fails to overwrite previous records
#- name: Create/ Update DNS host records in Infoblox (if applicable)
#  nios_host_record:
#    name: "{{item.fqdn}}"
#    ipv4:
#      - address: "{{ hostvars[item.hostname]['ansible_host'] }}"
#    state: present
#    provider:
#      host: "{{ infoblox[buildenv].server }}"
#      username: "{{ infoblox[buildenv].username }}"
#      password: "{{ infoblox[buildenv].password }}"


- name: Create/ Update DNS A records using nsupdate (if applicable)
  nsupdate:
    key_name: "{{bind9[buildenv].key_name}}"
    key_secret: "{{bind9[buildenv].key_secret}}"
    server: "{{bind9[buildenv].server}}"
    ttl: 60
    zone: "{{dns_tld_external}}"
    record: "{{item.hostname}}.{{cluster_vars.dns_zone_external | regex_replace('^(.*?)\\.' + dns_tld_external, '\\1')}}"
    value: "{{ hostvars[item.hostname]['ansible_host'] }}"
  become: false
  delegate_to: localhost
  run_once: true
  with_items: "{{ cluster_hosts_flat }}"
  when: (cluster_vars.dns_server is defined and cluster_vars.dns_server != "") and cluster_vars.dns_server == "nsupdate" and cluster_vars.dns_zone_external is defined and cluster_vars.dns_zone_external != ""

- name: Create/ Update DNS A records in Route53 (if applicable)
  route53:
    aws_access_key: "{{cluster_vars[buildenv].aws_access_key}}"
    aws_secret_key: "{{cluster_vars[buildenv].aws_secret_key}}"
    state: present
    zone: "{{cluster_vars.dns_zone_external}}"
    record: "{{item.hostname}}.{{cluster_vars.dns_zone_external}}"
    type: A
    ttl: 60
    value: "{{ hostvars[item.hostname]['ansible_host'] }}"
    private_zone: true
    overwrite: true
  become: false
  delegate_to: localhost
  run_once: true
  with_items: "{{ cluster_hosts_flat }}"
  when: (cluster_vars.dns_server is defined and cluster_vars.dns_server != "") and cluster_vars.dns_server=="route53" and (cluster_vars.dns_zone_external is defined and cluster_vars.dns_zone_external != "")

- name: Check that DNS has updated (or otherwise wait for it to do so)  [Note lookup('dig', new_fqdn) doesn't work - seems to cache - https://github.com/ansible/ansible/issues/44128]
  shell: "dig {{new_fqdn}} +short @{{bind9[buildenv].server}}"
  register: dig_result
  until: "dig_result.stdout == new_ip"
  retries: 60
  delay: 5
  with_items: "{{ cluster_hosts_flat }}"
  vars:
    new_fqdn: "{{item.hostname}}.{{cluster_vars.dns_zone_external}}."
    new_ip: "{{hostvars[item.hostname].ansible_host}}"
  become: false
  delegate_to: localhost
  run_once: true
  when: (cluster_vars.dns_server is defined and cluster_vars.dns_server != "" and cluster_vars.dns_server == "nsupdate") and (cluster_vars.dns_zone_external is defined and cluster_vars.dns_zone_external != "")

- name: "Create CNAME record"
  nsupdate:
    key_name: "{{bind9[buildenv].key_name}}"
    key_secret: "{{bind9[buildenv].key_secret}}"
    server: "{{bind9[buildenv].server}}"
    zone: "{{dns_tld_external}}"
    record: "{{item.hostname | regex_replace('-(?!.*-).*')}}.{{cluster_vars.dns_zone_external | regex_replace('^(.*?)\\.' + dns_tld_external, '\\1')}}"
    value:  "{{item.hostname}}.{{cluster_vars.dns_zone_external | regex_replace('^(.*?)\\.' + dns_tld_external, '\\1')}}"
    type: CNAME
    state: present
    ttl: 30
  with_items: "{{ cluster_hosts_flat }}"  
  when: cluster_vars.dns_server == "nsupdate" and instance_to_create is undefined and rescuing_instance is undefined
  delegate_to: localhost
  run_once: true

- name: "Create CNAME record"
  route53:
    aws_access_key: "{{cluster_vars[buildenv].aws_access_key}}"
    aws_secret_key: "{{cluster_vars[buildenv].aws_secret_key}}"
    state: present
    zone: "{{cluster_vars.dns_zone_external}}"
    record: "{{item.hostname | regex_replace('-(?!.*-)[0-9]{10}$')}}.{{cluster_vars.dns_zone_external}}"
    type: CNAME
    ttl: 30
    value: "{{item.hostname}}.{{cluster_vars.dns_zone_external}}"
    private_zone: true
    overwrite: true
  become: false
  delegate_to: localhost
  run_once: true   
  with_items: "{{ cluster_hosts_flat }}"  
  when: cluster_vars.dns_server == "route53" and instance_to_create is undefined and rescuing_instance is undefined
