- set_fact:
    auto_volumes_snapshots: "{{ auto_volumes_snapshots|default([]) + [_auto_instance] }}"
  loop: "{{ loop_instance.auto_volumes }}"
  vars:
    _auto_instance: "{% if 'snapshot_tags' in item.keys() %}{{ item|combine({'snapshot_id': _snapshot_id }) }}{% else %}{{ item }}{% endif %}"
    _snapshot_id: "{% if 'snapshot_tags' in item.keys() %}{{ (r_ebs_snapshots.snapshots|json_query(_query))[0].snapshot_id }}{% endif %}"
    _query: "{% if 'snapshot_tags' in item.keys() %}[?tags.backup_id == '{{ item.snapshot_tags['tag:backup_id']}}' && tags.node == '{{ loop_instance.index_per_hosttype }}']{% endif %}"

- set_fact:
    instance_with_auto_snapshots: "{{ instance_with_auto_snapshots|default({})|combine({'auto_volumes': auto_volumes_snapshots }) }}"

- set_fact:
    cluster_hosts_flat_snapshots: "{{ cluster_hosts_flat_snapshots|default([]) + [ _cluster_hosts_flat_snapshots_loop ]}}"
    auto_volumes_snapshots: []
  vars:
    _cluster_hosts_flat_snapshots_loop: "{{ loop_instance| combine(instance_with_auto_snapshots) }}"
