---

- name: Create GCP network and subnetwork (if -e create_gce_network=true)
  block:
    - name: Create GCP host network (if -e create_gce_network=true)
      gcp_compute_network:
        name: "{{cluster_vars[buildenv].vpc_network_name}}"
        auto_create_subnetworks: "{%- if cluster_vars[buildenv].vpc_subnet_name is defined and cluster_vars[buildenv].vpc_subnet_name != '' -%} false {%- else -%} true {%- endif -%}"
        project: "{{cluster_vars.project_id}}"
        auth_kind: "serviceaccount"
        service_account_file: "{{gcp_credentials_file}}"
      register: _gcp_compute_network

    - name: Create GCP host subnetwork (if -e create_gce_network=true)
      gcp_compute_subnetwork:
        name: "{{cluster_vars[buildenv].vpc_subnet_name}}"
        network: "{{_gcp_compute_network}}"
        project: "{{cluster_vars.project_id}}"
        auth_kind: "serviceaccount"
        service_account_file: "{{gcp_credentials_file}}"
      register: _gcp_compute_subnetwork
      when: (cluster_vars[buildenv].vpc_subnet_name is defined) and (cluster_vars[buildenv].vpc_subnet_name != "")
  when: create_gce_network is defined and create_gce_network|bool


- name: Create GCP firewalls
  block:
    - name: GCP network facts
      gcp_compute_network_info:
        filters:
          - "name = {{cluster_vars[buildenv].vpc_network_name}}"
        project: "{{cluster_vars.project_id}}"
        auth_kind: "serviceaccount"
        service_account_file: "{{gcp_credentials_file}}"
        scopes: ["https://www.googleapis.com/auth/compute.readonly"]
      register: gcp_compute_network_info

    - name: "Assert that {{cluster_vars[buildenv].vpc_network_name}} network exists"
      assert: { that: "gcp_compute_network_info['resources'] | length > 0", msg: "The {{cluster_vars[buildenv].vpc_network_name}} network must exist (create with ' -e create_gce_network=true')" }

    - name: GCP subnetwork facts
      gcp_compute_subnetwork_info:
        filters:
          - "name = {{cluster_vars[buildenv].vpc_subnet_name}}"
        project: "{{cluster_vars.project_id}}"
        auth_kind: "serviceaccount"
        service_account_file: "{{gcp_credentials_file}}"
        scopes: ["https://www.googleapis.com/auth/compute.readonly"]
        region: "{{cluster_vars.region}}"
      register: gcp_compute_subnetwork_info
      when: (cluster_vars[buildenv].vpc_subnet_name is defined) and (cluster_vars[buildenv].vpc_subnet_name != "")

    - name: "Assert that {{cluster_vars[buildenv].vpc_subnet_name}} subnet exists"
      assert: { that: "gcp_compute_subnetwork_info['resources'] | length > 0", msg: "The {{cluster_vars[buildenv].vpc_subnet_name}} subnet must exist" }
      when: (cluster_vars[buildenv].vpc_subnet_name is defined) and (cluster_vars[buildenv].vpc_subnet_name != "")

    - name: Create GCP cluster firewalls
      gcp_compute_firewall:
        name: "{{ item.name }}"
        target_tags: "{{cluster_vars.network_fw_tags}}"
        allowed: "{{ item.allowed }}"
        description: "{{ item.description }}"
        source_ranges: "{{ item.source_ranges | default([]) }}"
        source_tags: "{{ item.source_tags | default([]) }}"
        network: "{{gcp_compute_network_info['resources'][0]}}"
        auth_kind: "serviceaccount"
        service_account_file: "{{gcp_credentials_file}}"
        project: "{{cluster_vars.project_id}}"
      with_items: "{{ cluster_vars.firewall_rules }}"

- name: Generate public key from provided private key
  shell: ssh-keygen -y -f "{{ ansible_ssh_private_key_file }}"
  register: pubkey
  delegate_to: localhost
  run_once: true

- set_fact:
    gce_ssh_username: "{{ cliargs.remote_user }}"
    gce_ssh_pubkey: "{{ pubkey.stdout }}"

- name: Create GCP VMs asynchronously
  block:
    - name: Create GCP VMs asynchronously
      gcp_compute_instance:
        auth_kind: "serviceaccount"
        service_account_file: "{{gcp_credentials_file}}"
        project: "{{cluster_vars.project_id}}"
        zone: "{{cluster_vars.region}}-{{item.az_name}}"
        name: "{{item.hostname}}"
        machine_type: "{{item.flavor}}"
        disks: "{{_host_disks}}"
        metadata:
          startup-script: "{%- if cluster_vars.ssh_guard_whitelist is defined and cluster_vars.ssh_guard_whitelist | length > 0 -%}#! /bin/bash\n\n#Whitelist my inbound IPs\n[ -f /etc/sshguard/whitelist ] && echo \"{{cluster_vars.ssh_guard_whitelist | join ('\n')}}\" >>/etc/sshguard/whitelist && /bin/systemctl restart sshguard{%- endif -%}"
          ssh-keys: "{{ gce_ssh_username }}:{{ gce_ssh_pubkey }} {{ gce_ssh_username }}"
        labels:
          hosttype: "{{item.hosttype}}"
          env: "{{buildenv}}"
          release: "{%- if rescuing is defined and rescuing != \"false\" and instance_to_create is defined and instance_to_create == item.hostname -%}{{rescuing}}{%- elif instance_to_create is defined and instance_to_create == item.hostname -%}{{item.release}}{%- else -%}{{item.current_release}}{%- endif -%}"
          cluster_name: "{{cluster_name}}"
          cluster_suffix: "{{cluster_suffix}}"
          owner: "{{ lookup('env','USER')| lower  }}"
          maintenance_mode: "true"
          lifecycle_state: "current"
          deploy_status: "{%- if rescuing is defined and rescuing != \"false\" and instance_to_create is defined and instance_to_create == item.hostname -%}old{%- elif instance_to_create is defined and instance_to_create == item.hostname -%}new{%- else -%}{{item.current_deploy_status}}{%- endif -%}"
        network_interfaces:
          - network: "{{ gcp_compute_network_info['items'][0] | default({}) }}"
            subnetwork: "{{ gcp_compute_subnetwork_info['resources'][0] | default({}) }}"
            access_configs: "{%- if cluster_vars.assign_public_ip == 'yes' -%}[{\"name\": \"External NAT\", \"type\": \"ONE_TO_ONE_NAT\"}]{%- else -%}[]{%- endif -%}"
        tags: { items: "{{cluster_vars.network_fw_tags}}" }
        can_ip_forward : "{{cluster_vars.ip_forward}}"
        scheduling: { automatic_restart: yes, preemptible: "{{cluster_vars[buildenv].preemptible}}" }
        state: present
        deletion_protection: "{{cluster_vars[buildenv].deletion_protection}}"
      vars:
        __autodisksnames: "{%- if cluster_vars[buildenv].hosttype_vars[item.hosttype].auto_volumes | length -%}[{%- for vol in cluster_vars[buildenv].hosttype_vars[item.hosttype].auto_volumes -%}{%- set mountname = vol.mountpoint | regex_replace('.*\\/(.*)', '\\\\1') -%}{{vol|combine({'mountname': mountname})}}{% if not loop.last %},{% endif %}{%- endfor -%}]{%- else -%}[]{%- endif-%}"
        _autodisks: "{{__autodisksnames | to_json | from_json | json_query(\" [].{auto_delete: auto_delete, interface: interface, device_name: join('',[`\"+item.hostname+\"--`,mountname]), initialize_params: {disk_name: join('',[`\"+item.hostname+\"--`,mountname]), disk_size_gb: volume_size}} \") }}"
        _bootdisk: {auto_delete: true, boot: true, device_name: "{{ item.hostname }}--boot", initialize_params: {source_image: "{{cluster_vars.image}}", disk_name: "{{ item.hostname }}--boot", disk_size_gb: "{{item.rootvol_size}}"}}
        _host_disks: "{{[_bootdisk] + _autodisks}}"
      register: gcp_compute_instance
      run_once: true
      with_items: "{{cluster_hosts_target}}"
      async: 7200
      poll: 0

    - name: Wait for gce instance creation to complete
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: gce_jobs
      until: gce_jobs.finished
      delay: 3
      retries: 300
      with_items: "{{gcp_compute_instance.results}}"

    - name: set a fact containing newly-created hosts
      set_fact:
        cluster_hosts_target_created: "{{ gce_jobs.results | json_query(\"[?item.changed==`true`].item.item\") }}"
      delegate_to: localhost
      run_once: true


