---

- name: create/getimg/gcp | cluster_vars.image can either be an image location in its own right, or a filter to the latest image...
  block:
    - name: create/getimg/gcp | Attempt to find image from cluster_vars.image
      gcp_compute_image_info:
        filters:
          - "name = {{_image.name}}"
        project: "{{_image.project}}"
        auth_kind: "serviceaccount"
        service_account_file: "gcp__dev01-197706.json"
      register: r__gcp_compute_image_info__by_imageid
      vars:
        _image:
          project: "{{cluster_vars.image | regex_replace('.*projects/(.*?)/.*$', '\\1') }}"
          name: "{{cluster_vars.image | regex_replace('.*?images/(.*?)$', '\\1') | default('*') }}"

    - block:
        - debug: msg="create/getimg/gcp | Using '{{ repl_image.selfLink }}' as cluster_base_image"

        - name: create/getimg/gcp | Replace cluster_base_image with the latest image found in the cloud project
          set_fact:
            cluster_base_image: "{{ repl_image.selfLink }}"
      when: r__gcp_compute_image_info__by_imageid.resources | length > 1
      vars:
        repl_image: "{{ (r__gcp_compute_image_info__by_imageid.resources | sort(attribute='creationTimestamp'))[-1] }}"

