---

- name: Ensure that the 'release' tag/label is consistent within a cluster.  Perform this here (rather than roles/clusterverse/cluster_hosts/) to allow redeploy to change the version (i.e. after lifecycle_state is set to retiring).
  block:
    - name: current_release_versions
      debug: msg="{{current_release_versions}}"

    - block:
        - assert: { that: "current_release_versions | unique | length <= 1", msg: "Multiple 'current' release_versions running ({{current_release_versions | join(',')}}) - abort" }

        - assert: { that: "current_release_versions[0] == release_version", msg: "'version' tag/label applied differs from command line release_version: ('{{current_release_versions[0]}}' != '{{release_version}}') - abort" }
          when: (current_release_versions | length)  and  (release_version is defined and release_version != "")
      when: (skip_release_version_check is not defined)  or  (skip_release_version_check is defined  and  (not skip_release_version_check|bool))

    - name: Set the release_version to that defined in the current cluster
      set_fact:
        release_version: "{{ current_release_versions[0] | default('') }}"

    - debug: msg="release_version = {{release_version}}"
  vars:
    current_release_versions: "{{ cluster_hosts_state | json_query(\"[?tagslabels.lifecycle_state=='current' && tagslabels.release].tagslabels.release\") | default([]) }}"


- name: Manage base cluster image.  Either the same as existing cluster (if existing cluster exists), or the one defined in 'cluster_vars.image' (which may be a filter, not an image).  Perform this here (rather than roles/clusterverse/cluster_hosts/) to allow redeploy to change the version (i.e. after lifecycle_state is set to retiring).
  block:
    - name: _cluster_base_images
      debug: msg="{{_cluster_base_images}}"

    - block:
        - assert: { that: "_cluster_base_images | unique | length <= 1", fail_msg: "Multiple 'current' _cluster_base_images running ({{_cluster_base_images | join(',')}}) - abort" }

        - name: Set the cluster_base_image to that defined in the current cluster
          set_fact: { cluster_base_image: "{{ _cluster_base_images[0] | default('') }}" }

        - warn_str: msg="Using base image '{{cluster_base_image}}', which was found in use in the cluster, instead of defined 'cluster_vars.image' ({{cluster_vars.image}}), to avoid differing base images in cluster."
          when: cluster_vars.image != cluster_base_image
      when: _cluster_base_images | length

    - block:
        - name: Set the cluster_base_image to cluster_vars.image when no cluster already exists
          set_fact: { cluster_base_image: "{{ cluster_vars.image }}" }

        - name: Get cloud-specific base-image definition (if defined).
          include: "{{ item }}"
          loop: "{{ query('first_found', params) }}"
          vars: { params: { files: ["getimg_{{cluster_vars.type}}.yml"], skip: true } }
      when: _cluster_base_images | length == 0

    - debug: msg="cluster_base_image = {{cluster_base_image}}"
  vars:
    _cluster_base_images: "{{ cluster_hosts_state | json_query(\"[?tagslabels.lifecycle_state=='current' && cluster_base_image].cluster_base_image\") | default([]) }}"


- name: "Create {{cluster_vars.type}} cluster"
  include_tasks: "create_{{cluster_vars.type}}.yml"
  vars:
    # auto_volumes are normally a list of volumes per host (list of list).  We cannot iterate this within a non-nested ansible loop (with_items), so we denormalise/ flatten it into a new one-dimensional list, of each volume, as well as all the parent host information.
    cluster_hosts_target_denormalised_by_volume: |
      {% set res = [] -%}
      {%- for cht_host in cluster_hosts_target -%}
        {%- for autovol in cht_host.auto_volumes -%}
          {%- set elem = {} -%}
          {%- for cht_host_key in cht_host.keys() -%}
            {%- if cht_host_key != 'auto_volumes' -%}
              {%- set _ = elem.update({cht_host_key: cht_host[cht_host_key]}) -%}
            {%- else -%}
              {%- set _ = elem.update({'auto_volume': autovol}) -%}
            {%- endif -%}
          {%- endfor -%}
          {%- set _ = res.append(elem) -%}
        {%- endfor -%}
      {%- endfor -%}
      {{res}}
