---

- name: Deploy the cluster
  hosts: localhost
  connection: local
  roles:
    - { role: clusterverse/clean, tags: [clusterverse_clean], when: clean is defined }
    - { role: clusterverse/create, tags: [clusterverse_create] }
    - { role: clusterverse/dynamic_inventory, tags: [clusterverse_dynamic_inventory] }

- name: Configure the cluster
  hosts: all
  roles: [ { role: clusterverse/config, tags: [clusterverse_config] } ]

## Application roles
- name: Test application role
  hosts: all
  roles: [ { role: testrole, tags: [testrole] } ]
##

- name: Perform cluster readiness operations
  hosts: all
  roles: [ { role: clusterverse/readiness, tags: [clusterverse_readiness] } ]
