---

- name: clusterverse | Deploy the cluster
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - { name: "Get dependent roles via ansible-galaxy", local_action: "command ansible-galaxy install -fr requirements.yml", tags: ["always"] }

    - { include_role: { name: "clusterverse/clean", apply: { tags: ["clusterverse_clean"]} }, tags: ["clusterverse_clean"], when: "clean is defined" }
    - { include_role: { name: "clusterverse/create", apply: { tags: ["clusterverse_create"]} }, tags: ["clusterverse_create"] }
    - { include_role: { name: "clusterverse/dynamic_inventory", apply: { tags: ["clusterverse_dynamic_inventory"]} }, tags: ["clusterverse_dynamic_inventory"] }

- name: clusterverse | Wait for SSH connections
  hosts: all
  gather_facts: no
  tasks: [ {wait_for_connection: "", tags: ["always"] } ]

- name: clusterverse | Configure the cluster
  hosts: all
  tasks: [ { include_role: { name: "clusterverse/config", apply: { tags: ["clusterverse_config"]} }, tags: ["clusterverse_config"] } ]

## Application roles
- name: Application roles
  hosts: all
  tasks:
    - { include_role: { name: "testrole", apply: { tags: ["testrole"]} }, tags: ["testrole"] }
##

- name: clusterverse | Perform cluster readiness operations
  hosts: localhost
  connection: local
  tasks: [ { include_role: { name: "clusterverse/readiness", apply: { tags: ["clusterverse_readiness"]} }, tags: ["clusterverse_readiness"] } ]
