---

- name: Redeploy (reprovision one at a time).
  hosts: localhost
  connection: local
  tasks:
    - name: Run redeploy
      import_role:
        name: clusterverse/redeploy
      vars:
        mainclusteryml: "cluster.yml"
        predeleterole: ""
