---

- name: Redeploy
  hosts: localhost
  connection: local
  tasks:
    - name: Run redeploy
      import_role:
        name: clusterverse/redeploy
      vars:
        mainclusteryml: "cluster.yml"
        predeleterole: "testrole/_redeploy"
