---

- name: Clean the cluster
  hosts: localhost
  connection: local
  roles:
    - role: clusterverse/clean
      when: clean is defined and clean|bool
  tags: clusterverse_clean

- name: Deploy the cluster
  hosts: localhost
  connection: local
  roles:
    - role: clusterverse/create
  tags: clusterverse_create

- name: Perform config on the cluster
  hosts: all
  roles:
    - role: clusterverse/config
  tags: clusterverse_config

## ...
## Application roles
## ...

- name: Perform cluster readiness operations (e.g. remove maintenance_mode tag from VMs).
  hosts: all
  roles:
    - role: clusterverse/readiness
  tags: clusterverse_readiness

