---

- name: Clean the cluster
  hosts: localhost
  connection: local
  become: false
  gather_facts: true
  roles:
    - role: clusterbuild/clean
      when: clean is defined and clean|bool
  tags: clusterbuild_clean

- name: Deploy the cluster
  hosts: localhost
  connection: local
  become: false
  gather_facts: true
  roles:
    - role: clusterbuild/create
  tags: clusterbuild_create

- name: Wait for target connection to cluster nodes (NOTE - This cannot be within clusterbuild/config as that gathers facts, which needs the connection already)
  hosts: all
  gather_facts: false
  tasks:
    - wait_for_connection:
  tags: clusterbuild_config

- name: Perform config on the cluster
  hosts: all
  become: false
  roles:
    - role: clusterbuild/config
  tags: clusterbuild_config

## ...
## Application roles
## ...

- name: Perform cluster readiness operations (e.g. remove maintenance_mode tag from VMs).
  hosts: all
  roles:
    - role: clusterbuild/readiness
  tags: clusterbuild_readiness

