---

- name: Clean the cluster
  hosts: localhost
  connection: local
  become: false
  gather_facts: true
  roles:
    - role: clusterverse/clean
      when: clean is defined and clean|bool
  tags: clusterverse_clean

- name: Deploy the cluster
  hosts: localhost
  connection: local
  become: false
  gather_facts: true
  roles:
    - role: clusterverse/create
  tags: clusterverse_create

- name: Wait for target connection to cluster nodes (NOTE - This cannot be within clusterverse/config as that gathers facts, which needs the connection already)
  hosts: all
  gather_facts: false
  tasks:
    - wait_for_connection:
  tags: clusterverse_config

- name: Perform config on the cluster
  hosts: all
  become: false
  roles:
    - role: clusterverse/config
  tags: clusterverse_config

## ...
## Application roles
## ...

- name: Perform cluster readiness operations (e.g. remove maintenance_mode tag from VMs).
  hosts: all
  roles:
    - role: clusterverse/readiness
  tags: clusterverse_readiness

