---

- name: Preflight check
  hosts: localhost:all
  connection: local
  gather_facts: false
  tasks:
    - assert: { that: "clean is not defined", msg: "Must not set the 'clean' variable for a redeploy" }
    - assert: { that: "canary is defined and (canary is defined and canary in ['start', 'finish', 'none'])", msg: "Canary must be 'start', 'finish' or 'none'" }
  tags: always

- name: Redeploy (destroy and reprovision one at a time).
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tasks:
    - name: Run redeploy.
      include_role:
        name: clusterbuild/redeploy
      vars:
        mainclusteryml: "cluster.yml"
