---

- name: Redeploy (reprovision one at a time).
  hosts: localhost
  connection: local
  become: false
  gather_facts: true
  tasks:
    - name: Run redeploy
      import_role:
        name: clusterbuild/redeploy
      vars:
        mainclusteryml: "cluster.yml"
        predeleterole: ""
