---

- debug: msg="Stop {{host_to_del.hostname}}"

- name: Delete GCE instance
  block:
    - name: Get GCP instance facts
      gcp_compute_instance_facts:
        zone: "{{cluster_vars[clusterid].region}}-{{host_to_del.hostname | regex_replace('.*-([a-z])[0-9]-.*', '\\1')}}"
        filters:
          - "name = {{host_to_del.hostname}}*"
          - "status = RUNNING"
        project: "{{cluster_vars[clusterid].project_id}}"
        auth_kind: "serviceaccount"
        service_account_file: "{{gcp_credentials_file}}"
        scopes: ["https://www.googleapis.com/auth/compute.readonly"]
      register: gcp_compute_instance_facts
      delegate_to: localhost

    - name: Delete DNS A records using nsupdate (if applicable)
      nsupdate:
        key_name: "{{bind9.key_name}}"
        key_secret: "{{bind9.key_secret}}"
        server: "{{bind9.server}}"
        zone: "{{dns_tld_external}}"
        state: "absent"
        record: "{{host_to_del.hostname}}.{{cluster_vars[clusterid].dns_zone_external | regex_replace('^(.*?)\\.' + dns_tld_external, '\\1')}}"
      when: cluster_vars[clusterid].dns_server == "nsupdate" and cluster_vars[clusterid].dns_zone_external is defined and cluster_vars[clusterid].dns_zone_external != ""

    - name: Delete DNS entries from route53
      block:
        - name: Get DNS entries from route53
          route53:
            state: "get"
            zone: "{{cluster_vars[clusterid].dns_zone_external}}"
            record: "{{cluster_vars[clusterid].region}}-{{cluster_hosts_flat  | json_query('[? hostname == `' + host_to_del.hostname + '`].az_name|[0]')}}"
            type: "A"
          register: dns_rec

        - name: Remove DNS entries from route53
          route53:
            state: "absent"
            zone: "{{ item.set.zone }}"
            record: "{{ item.set.record }}"
            type: "{{ item.set.type }}"
            ttl: "{{ item.set.ttl }}"
            value: ["{{ item.set.value }}"]
          with_items: "{{ dns_rec.results }}"
          when: item.set.value is defined
      when: cluster_vars[clusterid].dns_server == "route53" and cluster_vars[clusterid].dns_zone_external is defined and cluster_vars[clusterid].dns_zone_external != ""

    - name: Delete GCE VM
      gcp_compute_instance:
        name: "{{host_to_del.hostname}}"
        project: "{{cluster_vars[clusterid].project_id}}"
        zone: "{{cluster_vars[clusterid].region}}-{{host_to_del.hostname | regex_replace('.*-([a-z])[0-9]-.*', '\\1')}}"
        auth_kind: "serviceaccount"
        service_account_file: "{{gcp_credentials_file}}"
        status: "absent"
      register: gcp_compute_instance
      async: 7200
      poll: 0
      delegate_to: localhost

    - name: Wait for gce instance stop to complete
      async_status:
        jid: "{{ gcp_compute_instance.ansible_job_id }}"
      register: gcp_jobs
      until: gcp_jobs.finished
      retries: 300
      delegate_to: localhost
