---

- name: Delete EC2 instances
  block:
    - name: get existing instance facts
      ec2_instance_facts:
        filters:
          "tag:Name": "{{item.hostname}}"
          "instance-state-name": ["running", "stopped"]
        aws_access_key: "{{cluster_vars[buildenv].aws_access_key}}"
        aws_secret_key: "{{cluster_vars[buildenv].aws_secret_key}}"
        region: "{{cluster_vars.region}}"
      register: ec2_existing
      delegate_to: localhost
      with_items: "{{ cluster_hosts_flat }}"

    - set_fact:
        uids_to_del: "{{ec2_existing | json_query(\"results[].instances[].{state: state.name, id: instance_id}\") }}"

    - name: Remove EC2 instances termination protection
      ec2:
        aws_access_key: "{{cluster_vars[buildenv].aws_access_key}}"
        aws_secret_key: "{{cluster_vars[buildenv].aws_secret_key}}"
        region: "{{ cluster_vars.region }}"
        state: "{{ item.state }}"
        termination_protection: "no"
        instance_ids: "{{ item.id }}"
      with_items: "{{ uids_to_del }}"

    - name: set maintenance_mode to true
      ec2_tag:
        aws_access_key: "{{cluster_vars[buildenv].aws_access_key}}"
        aws_secret_key: "{{cluster_vars[buildenv].aws_secret_key}}"
        region: "{{cluster_vars.region}}"
        resource: "{{ item.id }}"
        tags:
          maintenance_mode: "true"
      delegate_to: localhost
      run_once: true
      with_items: "{{ uids_to_del }}"

    - name: Delete EC2 instances
      ec2:
        aws_access_key: "{{cluster_vars[buildenv].aws_access_key}}"
        aws_secret_key: "{{cluster_vars[buildenv].aws_secret_key}}"
        region: "{{ cluster_vars.region }}"
        state: "absent"
        instance_ids: "{{ uids_to_del | json_query(\"[].id\") }}"
        wait: true
      when: uids_to_del|length > 0


- name: Delete security group
  ec2_group:
    name: "{{ cluster_name }}-sg"
    region: "{{cluster_vars.region}}"
    vpc_id: "{{vpc_id}}"
    aws_access_key: "{{cluster_vars[buildenv].aws_access_key}}"
    aws_secret_key: "{{cluster_vars[buildenv].aws_secret_key}}"
    state: absent
