---

- name: Delete GCE VMs asynchronously
  gcp_compute_instance:
    name: "{{item.hostname}}"
    project: "{{cluster_vars[clusterid].project_id}}"
    zone: "{{cluster_vars[clusterid].region}}-{{item.az_name}}"
    auth_kind: "serviceaccount"
    service_account_file: "{{gcp_credentials_file}}"
    state: "absent"
  register: gcp_compute_instance
  with_items: "{{cluster_hosts_flat}}"
  async: 7200
  poll: 0

- name: Wait for gce instance deletion to complete
  async_status:
    jid: "{{ item.ansible_job_id }}"
  register: gcp_jobs
  until: gcp_jobs.finished
  retries: 300
  with_items: "{{gcp_compute_instance.results}}"

- name: Delete GCP cluster firewalls
  gcp_compute_firewall:
    name: "{{ item.name }}"
    state: "absent"
    auth_kind: "serviceaccount"
    service_account_file: "{{gcp_credentials_file}}"
    project: "{{cluster_vars[clusterid].project_id}}"
  with_items: "{{ cluster_vars[clusterid].firewall_rules }}"

- name: Delete the GCP network (if -e create_gce_network=true)
  gcp_compute_network:
    name: "{{cluster_vars[clusterid][buildenv].vpc_network_name}}"
    auth_kind: "serviceaccount"
    service_account_file: "{{gcp_credentials_file}}"
    project: "{{cluster_vars[clusterid].project_id}}"
    state: absent
  when: create_gce_network is defined and create_gce_network|bool
