---

- include_tasks: openstack.yml
  when: cluster_vars[clusterid].type == "openstack"

- include_tasks: gce.yml
  when: cluster_vars[clusterid].type == "gce"

- include_tasks: aws.yml
  when: cluster_vars[clusterid].type == "aws"

- name: Delete DNS entries from infoblox
  infoblox:
    server: "{{ infoblox.server }}"
    username: "{{ infoblox.username }}"
    password: "{{ infoblox.password }}"
    action: delete_a_record
    name: "{{item.hostname}}.{{cluster_vars[clusterid].dns_zone_external}}"
  with_items: "{{ cluster_hosts_flat }}"
  when: cluster_vars[clusterid].dns_server == "infoblox" and cluster_vars[clusterid].dns_zone_external is defined and cluster_vars[clusterid].dns_zone_external != ""

## Can't use this unless we use the same creation (which doesn't work properly)
#- name: Delete DNS entries from infoblox
#  nios_host_record:
#    name: "{{ item.hostname}}.{{cluster_vars[clusterid].dns_zone_external}}"
#    state: absent
#    provider:
#      host: "{{ infoblox.server }}"
#      username: "{{ infoblox.username }}"
#      password: "{{ infoblox.password }}"
  
- name: Delete DNS A records using nsupdate (if applicable)
  nsupdate:
    key_name: "{{bind9.key_name}}"
    key_secret: "{{bind9.key_secret}}"
    server: "{{bind9.server}}"
    zone: "{{dns_tld_external}}"
    state: "absent"
    record: "{{item.hostname}}.{{cluster_vars[clusterid].dns_zone_external | regex_replace('^(.*?)\\.' + dns_tld_external, '\\1')}}"
  with_items: "{{ cluster_hosts_flat }}"
  when: cluster_vars[clusterid].dns_server == "nsupdate" and cluster_vars[clusterid].dns_zone_external is defined and cluster_vars[clusterid].dns_zone_external != ""

- name: "Delete CNAME records"
  nsupdate:
    key_name: "{{bind9.key_name}}"
    key_secret: "{{bind9.key_secret}}"
    server: "{{bind9.server}}"
    zone: "{{dns_tld_external}}"
    record: "{{item.hostname | regex_replace('-(?!.*-).*')}}.{{cluster_vars[clusterid].dns_zone_external | regex_replace('^(.*?)\\.' + dns_tld_external, '\\1')}}"
    value:  "{{item.hostname}}.{{cluster_vars[clusterid].dns_zone_external | regex_replace('^(.*?)\\.' + dns_tld_external, '\\1')}}"
    type: CNAME
    state: absent
  with_items: "{{ cluster_hosts_flat }}"  
  when: cluster_vars[clusterid].dns_server == "nsupdate" and (instance_to_create is undefined or rescuing_instance is undefined)
  delegate_to: localhost  

- name: Delete DNS entries from route53
  block:
  - name: Get DNS entries from route53
    route53:
      state: "get"
      zone: "{{cluster_vars[clusterid].dns_zone_external}}"
      record: "{{item.hostname}}.{{cluster_vars[clusterid].dns_zone_external}}"
      type: "A"
    register: dns_rec
    with_items: "{{ cluster_hosts_flat }}"

  - name: Remove DNS entries from route53
    route53:
      state: "absent"
      zone: "{{ item.set.zone }}"
      record: "{{ item.set.record }}"
      type: "{{ item.set.type }}"
      ttl: "{{ item.set.ttl }}"
      value: ["{{ item.set.value }}"]
    with_items: "{{ dns_rec.results }}"
    when: item.set.value is defined
  when: cluster_vars[clusterid].dns_server == "route53" and cluster_vars[clusterid].dns_zone_external is defined and cluster_vars[clusterid].dns_zone_external != ""

- name: empty the inventory file
  block:
    - stat: path={{inventory_file}}
      register: stat_inventory_file
      when: inventory_file is defined

    - set_fact:
        new_inventory_file: "{{ inventory_file if (((stat_inventory_file.stat is defined and stat_inventory_file.stat.exists) or (stat_inventory_file.skipped is defined and stat_inventory_file.skipped)) and inventory_dir is defined and inventory_dir==playbook_dir) else playbook_dir + '/inventory_' + cluster_name }}"

    # Check the inventory_dir==playbook_dir, because the default inventory is /etc/ansible/hosts
    - name: Create (empty) inventory file
      copy:
        content: ""
        dest: "{{new_inventory_file}}"
        force: yes

    - name: Refresh inventory
      meta: refresh_inventory
