---

- name: "Delete hostname/ ip from DNS"
  shell: openstack recordset delete {{os_zone_id}} {{item.id}}
  vars:
    queryvar: "[?name=='{{fqdn}}.']"
  with_items: "{{ os_all_dns|json_query(queryvar) }}"
  when: "fqdn in item.name"
  become: false
  delegate_to: localhost
  run_once: true
