---
## Default user vars - in general to be provided by Jenkins
clusterid: ""                     # Must be an index into cluster_vars in cluster_vars.yml
buildenv: ""                      # Must be an index into cluster_vars[clusterid].host_vars in cluster_vars.yml

app_class: "test"                 # The class of application - applies to the fqdn
clustername_prefix: "qwerty"      # Gives a customised name for identification purposes (it is part of cluster_name, and identifies load balancers etc in cloud environments)

dns_tld_external: "example.com"   # Top-level domain (above the level defined per clusterid)


# The global {{cluster_name}} is prefixed with "{{clustername_prefix}}-" if clustername_prefix is defined
cluster_name: "{{clustername_prefix}}{% if not clustername_prefix | regex_search('.*-$') %}-{% endif -%}{{buildenv}}"

prometheus_node_exporter_install: true    #Whether to install the prometheus node_exporter tool
prometheus_node_exporter_port: 19100      #Port to export metrics to.  The default (9100), conflicts with a Couchbase port, and prevents couchbase working.
prometheus_node_exporter_version: 0.15.2  #Version of prometheus node_exporter tool to install

filebeat_install: true
filebeat_version: 6.2.4

reboot_on_package_upgrade: false

# Infoblox Service API user credentials and configurations
infoblox:
  server:
  api_version:
  username:
  password:
