---
# Openstack and Google Cloud credentials lookup
os_username: "{{ lookup('env','OS_USERNAME') }}"
os_password: "{{ lookup('env','OS_PASSWORD') }}"
gcp_credentials_file: "{{ lookup('env','GCP_CREDENTIALS') | default('/dev/null', true) }}"
gcp_credentials_json: "{{ lookup('file', gcp_credentials_file) | default({'project_id': 'GCP_CREDENTIALS__NOT_SET','client_email': 'GCP_CREDENTIALS__NOT_SET'}, true) }}"


cluster_vars:
  aws_eu_west_1:
    type: aws
#    image: "ami-3548444c"            #CentOS Linux 7 x86_64 HVM EBS ENA 1805_01-b7ee8a69-ee97-4a49-9e68-afaee216db2e-ami-77ec9308.4
#    image: "ami-0181f8d9b6f098ec4"  #ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20180814
    image: "ami-0ee06eb8d6eebcde0"  #ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-20180823
    region: "eu-west-1"
    assign_public_ip: "no"
    dns_zone_internal: "eu-west-1.compute.internal"
    dns_zone_external: "{%- if dns_tld_external -%}  aws_euw1.{{app_class}}.{{buildenv}}.{{dns_tld_external}}  {%- endif -%}"
    dns_server: "nsupdate"    # Specify DNS server. nsupdate, infoblox or openstack (on openstack) supported.  If empty string is specified, no DNS will be added.
    instance_profile_name: "vpc_lock_{{buildenv}}"
    secgroups_existing: []
    secgroup_new:
      - proto: "tcp"
        ports: [22]
        cidr_ip: 10.0.0.0/8
        rule_desc: "SSH Access"
      - proto: "tcp"
        ports: ["{{prometheus_node_exporter_port}}"]
        group_name: ["{{buildenv}}-private-sg"]
        rule_desc: "Prometheus instances attached to {{buildenv}}-private-sg can access the exporter port(s)."
      - proto: all
        group_name: ["{{ cluster_name }}-sg"]
        rule_desc: "Access from all VMs attached to the {{ cluster_name }}-sg group"
    dev:
      host_vars:
        test: {count_per_az: 1, az: ["a", "b"], flavor: t2.micro, ephemeral_volumes: [{"device_name": "/dev/sdb", mountpoint: "/dev/xvdb", "volume_type": "gp2", "volume_size": 2, "delete_on_termination": true}]}
      aws_access_key:
      aws_secret_key:
      vpc_name: "{{buildenv}}"
      vpc_subnet_name_prefix: "{{buildenv}}-infrastructure-subnet"
      key_name: "{{buildenv}}-key"
      termination_protection: "yes"
    stage:
      host_vars:
        test: {count_per_az: 1, az: ["a", "b"], flavor: t2.micro, ephemeral_volumes: [{"device_name": "/dev/sdb", mountpoint: "/dev/xvdb", "volume_type": "gp2", "volume_size": 2, "delete_on_termination": true}]}
      aws_access_key:
      aws_secret_key:
      vpc_name: "{{buildenv}}"
      vpc_subnet_name_prefix: "{{buildenv}}-infrastructure-subnet"
      key_name: "{{buildenv}}-key"
      termination_protection: "yes"
    prod:
      host_vars:
        test: {count_per_az: 1, az: ["a", "b"], flavor: t2.micro, ephemeral_volumes: [{"device_name": "/dev/sdb", mountpoint: "/dev/xvdb", "volume_type": "gp2", "volume_size": 2, "delete_on_termination": true}]}
      aws_access_key:
      aws_secret_key:
      vpc_name: "{{buildenv}}"
      vpc_subnet_name_prefix: "{{buildenv}}-infrastructure-subnet"
      key_name: "{{buildenv}}-key"
      termination_protection: "yes"
    tools:
      host_vars:
        test: {count_per_az: 1, az: ["a", "b"], flavor: t2.micro, ephemeral_volumes: [{"device_name": "/dev/sdb", mountpoint: "/dev/xvdb", "volume_type": "gp2", "volume_size": 2, "delete_on_termination": true}]}
      aws_access_key:
      aws_secret_key:
      vpc_name: "{{buildenv}}"
      vpc_subnet_name_prefix: "{{buildenv}}-infrastructure-subnet"
      key_name: "{{buildenv}}-key"
      termination_protection: "yes"
    sandbox:
      host_vars:
        test: {count_per_az: 1, az: ["a", "b", "c"], flavor: t2.micro, ephemeral_volumes: []}
      aws_access_key:
      aws_secret_key:
      vpc_name: "{{buildenv}}"
      vpc_subnet_name_prefix: "{{buildenv}}-scratch-subnet"
      key_name: "{{buildenv}}-key"
      termination_protection: "yes"

  m25_lsd_slo:
    type: openstack
    image: "centos7"    #OR "CentOS-7-cloudimg-x64-20170612",  "Ubuntu-1604-Xenial-cloudimg-x64-20170621"
    region: "SLO"
#    dns_zone_internal: ""
    dns_zone_external: "{%- if dns_tld_external -%}  os_m25s.{{app_class}}.{{buildenv}}.{{dns_tld_external}}  {%- endif -%}"
    dns_server: "openstack"    # Specify DNS server. infoblox or openstack (on openstack) supported.  If empty string is specified, no DNS will be added.
    dev:
      host_vars:
        test: {count_per_az: 1, az: ["az1", "az2"], flavor: m1.1c.1g, rootvol_size: "10"}
    prod:
      host_vars:
        test: {count_per_az: 1, az: ["az1", "az2"], flavor: m1.1c.1g, rootvol_size: "10"}
    cloud_provider: "external"
    network: "k8s_dev"
    security_group: "wide-open"
    key_name: "{{os_username}}"
    floating_ip_pools: "vlan3321"
    OS_AUTH_URL:
    OS_TENANT_ID:
    OS_TENANT_NAME:
    OS_PROJECT_NAME:

  gce_eu_west1:
    type: gce
    region: "europe-west1"
    dns_zone_internal: "c.{{gcp_credentials_json.project_id}}.internal"
    dns_zone_external: "{%- if dns_tld_external -%}  gce_euw1.{{app_class}}.{{buildenv}}.{{dns_tld_external}}  {%- endif -%}"
    dns_server: "infoblox"    # Specify DNS server. infoblox or openstack (on openstack) supported.  If empty string is specified, no DNS will be added.
    dev:
      host_vars:
        test: {count_per_az: 1, az: ["b", "c"], flavor: f1-micro, rootvol_size: "10"}
    cloud_provider: "gce"
    credentials_file: "{{ gcp_credentials_file }}"
    service_account_email: "{{gcp_credentials_json.client_email}}"
    project_id: "{{gcp_credentials_json.project_id}}"
    #image: "centos-7"
    image: "ubuntu-1804"
    preemptible: "false"
    ip_forward: "true"
    external_ip: "ephemeral"
    ext_firewall_src_range: []
