---

- debug: msg="Attempting to redeploy {{host_to_del}}"

- include_tasks: gce_del.yml
  when: cluster_vars.type == "gce"

- include_tasks: aws_del.yml
  when: cluster_vars.type == "aws"

- name: "set argument variables for {{mainclusteryml}}"
  set_fact:
    maincluster_yml_args: "{{ (argv | join(' ')) | regex_replace('redeploy.yml', mainclusteryml) }}"

- name: "run {{mainclusteryml}}"
  shell: "{{maincluster_yml_args}}"
  register: r_mainclusteryml

- debug: msg={{r_mainclusteryml}}