---

- debug: msg="Delete {{host_to_del.hostname}}"

- name: get existing instance
  ec2_instance_facts:
    filters:
      "tag:Name": "{{ host_to_del.hostname }}"
      "instance-state-name": ["running", "stopped"]
    aws_access_key: "{{cluster_vars[buildenv].aws_access_key}}"
    aws_secret_key: "{{cluster_vars[buildenv].aws_secret_key}}"
    region: "{{cluster_vars.region}}"
  register: ec2_instance_facts
  delegate_to: localhost
  run_once: true

- name: aws_del | Delete EC2 instance
  ec2:
    aws_access_key: "{{cluster_vars[buildenv].aws_access_key}}"
    aws_secret_key: "{{cluster_vars[buildenv].aws_secret_key}}"
    region: "{{ cluster_vars.region }}"
    state: "absent"
    instance_ids: ["{{ ec2_instance_facts.instances[0].instance_id }}"]
    wait: true
  when: (ec2_instance_facts.instances is defined) and (ec2_instance_facts.instances | length>0) and (ec2_instance_facts.instances[0].instance_id is defined)
  delegate_to: localhost
  run_once: true
