---

- debug: msg="Delete {{host_to_del.hostname}}"

- name: Get GCP instance facts
  gcp_compute_instance_facts:
    zone: "{{cluster_vars[clusterid].region}}-{{host_to_del.hostname | regex_replace('.*-([a-z])[0-9]-.*', '\\1')}}"
    filters:
      - "name = {{host_to_del.hostname}}*"
      - "status = RUNNING"
    project: "{{cluster_vars[clusterid].project_id}}"
    auth_kind: "serviceaccount"
    service_account_file: "{{gcp_credentials_file}}"
    scopes: ["https://www.googleapis.com/auth/compute.readonly"]
  register: gcp_compute_instance_facts
  delegate_to: localhost

- name: Remove deletion protection
  command: "gcloud compute instances update {{host_to_del.hostname}} --no-deletion-protection --zone {{cluster_vars[clusterid].region}}-{{host_to_del.hostname | regex_replace('.*-([a-z])[0-9]-.*', '\\1')}}"
  when: "cluster_vars[buildenv].deletion_protection == 'yes'"

#- name: Remove deletion protection (broken)
#  gcp_compute_instance:
#    name: "{{host_to_del.hostname}}"
#    project: "{{cluster_vars.project_id}}"
#    zone: "{{cluster_vars[clusterid].region}}-{{host_to_del.hostname | regex_replace('.*-([a-z])[0-9]-.*', '\\1')}}"
#    auth_kind: "serviceaccount"
#    service_account_file: "{{gcp_credentials_file}}"
#    deletion_protection: no

- name: Delete GCE VM
  gcp_compute_instance:
    name: "{{host_to_del.hostname}}"
    project: "{{cluster_vars[clusterid].project_id}}"
    zone: "{{cluster_vars[clusterid].region}}-{{host_to_del.hostname | regex_replace('.*-([a-z])[0-9]-.*', '\\1')}}"
    auth_kind: "serviceaccount"
    service_account_file: "{{gcp_credentials_file}}"
    status: "absent"
  register: gcp_compute_instance
