---

- name: Get the state of the VMs in the cluster
  include_tasks: get_cluster_hosts_state.yml


- name: Set the cluster_suffix based on the existing cluster; if there is no existing cluster, create cluster_suffix anew.  Overridden by command line for some redeploy schemes, e.g. '-e cluster_suffix=1234'
  block:
    - assert: { that: "cluster_suffixes_current | unique | length <= 1", msg: "Multiple 'current' suffixes running ({{cluster_suffixes_current | join(',')}}) - abort" }

    - name: Set cluster_suffix to suffix of current live VMs
      set_fact:
        cluster_suffix: "{{cluster_suffixes_current[0]}}"
      when: cluster_suffixes_current | unique | length==1

    - name: Create new cluster_suffix
      set_fact:
        cluster_suffix: "{{ansible_date_time.epoch}}"
      when: cluster_suffixes_current | unique | length==0

    - debug: msg="cluster_suffix = {{cluster_suffix}}"
  vars:
    cluster_suffixes_current: "{{ cluster_hosts_state | json_query(\"[?tagslabels.lifecycle_state=='current'].tagslabels.cluster_suffix\") }}"


- name: Create cluster_hosts_flat from the cluster definition in cluster_vars, and add cloud-specific modifications
  include_tasks: get_cluster_hosts_target.yml
