---

- name: Change operational_state label
  block:
    - name: Get existing GCP instance info (per AZ)
      gcp_compute_instance_info:
        zone: "{{cluster_vars.region}}-{{item}}"
        filters:
          - "labels.cluster_name = {{cluster_name}}"
        project: "{{cluster_vars.project_id}}"
        auth_kind: "serviceaccount"
        service_account_file: "{{gcp_credentials_file}}"
        scopes: ["https://www.googleapis.com/auth/compute.readonly"]
      with_items: "{{ cluster_vars[buildenv].hosttype_vars | json_query(\"*[vms_by_az][][keys(@)][][]\") | unique }}"
      register: r_gcp_compute_instance_info
      delegate_to: localhost
      run_once: true

    - name: Change operational_state label
      gcp_compute_instance:
        name: "{{item.name}}"
        project: "{{cluster_vars.project_id}}"
        zone: "{{item.zone | regex_replace('^.*/(.*)$', '\\1')}}"
        auth_kind: "serviceaccount"
        service_account_file: "{{gcp_credentials_file}}"
        deletion_protection: "{{cluster_vars[buildenv].deletion_protection}}"
        status: "{{item.status}}"
        labels: "{{ item.labels | combine({'operational_state': new_state}) }}"
      with_items: "{{ v__items }}"
      vars:
        v__items: "{%- if old_state != '_all_'-%}{{r_gcp_compute_instance_info.results | json_query(\"[].resources[?labels.operational_state=='\"+old_state+\"'][]\")}}{%- else -%}{{r_gcp_compute_instance_info.results | json_query(\"[].resources[]\")}}{%- endif -%}"
