---

# Create an array of dictionaries containing all the hostnames PER-AZ (i.e. couchbase-dev-node-a0, couchbase-dev-master-a1, couchbase-dev-master-b0, couchbase-dev-master-b1 etc) to be created:
- set_fact:
    cluster_hosts_flat: |
      {% set res = [] -%}
      {%- for hostttype in cluster_vars[clusterid][buildenv].host_vars.keys() -%}
        {%- if cluster_vars[clusterid][buildenv].host_vars.keys() | length > 1 -%}
          {%- set hosttype_str = hostttype + "-" -%}
        {%- else -%}
          {%- set hosttype_str = "" -%}
        {%- endif -%}
        {%- for azname in cluster_vars[clusterid][buildenv].host_vars[hostttype].az -%}
          {%- for number in range(0,cluster_vars[clusterid][buildenv].host_vars[hostttype].count_per_az|int) -%}
            {% set _dummy = res.extend([{
              'type': hostttype,
              'hostname': cluster_name + '-' + hosttype_str + azname + number|string,
              'az_name': azname|string,
              'fqdn': cluster_name + '-' + hosttype_str + azname + number|string + "." + cluster_vars[clusterid].type + "." + cluster_vars[clusterid].region_short + azname|string + "." + app_class + "." + buildenv + "." + cluster_vars[clusterid].dns_tld_external,
              'flavor': cluster_vars[clusterid][buildenv].host_vars[hostttype].flavor
              }]) -%}
          {%- endfor %}
        {%- endfor %}
      {%- endfor %}
      {{ res }}

#- debug: msg={{cluster_hosts_flat}}

- name: get other hosts
  set_fact:
    other_hosts: "{{ (hostvars[ansible_play_hosts[0]].cluster_hosts_flat | json_query('[].hostname') + ['localhost']) | unique | symmetric_difference(ansible_play_hosts) }}"
  run_once: true

- name: set the cluster_hosts_flat variable on all other hosts
  set_fact:
    cluster_hosts_flat: "{{hostvars[ansible_play_hosts[0]].cluster_hosts_flat}}"
    cacheable: true
  delegate_to: "{{item}}"
  run_once: true
  with_items: "{{ other_hosts }}"

- include_tasks: aws.yml
  when: cluster_vars[clusterid].type == "aws"

- include_tasks: openstack.yml
  when: cluster_vars[clusterid].type == "openstack"

- include_tasks: gce.yml
  when: cluster_vars[clusterid].type == "gce"

#- debug: msg={{cluster_hosts_flat}}

#- set_fact:
#    cluster_hosts_dict: "{{cluster_hosts_flat | dict_agg('hostname')}}"
#
#- debug: msg={{cluster_hosts_dict}}
