---

## Should be a single command to create/update DNS in openstack, but apparently is not supported in all openstack cloud libraries.  The problem is that the 'zone' parameter is expected by one library to be an ID, and by another to be the Name.
#- name: "Add {{fqdn}} to openstack dns"
#  os_recordset:
#    auth_type: password
#    auth:
#      auth_url: "{{cluster_vars.OS_AUTH_URL}}"
#      tenant_id: "{{cluster_vars.OS_TENANT_ID}}"
#      tenant_name: "{{cluster_vars.OS_TENANT_NAME}}"
#      project_name: "{{cluster_vars.OS_PROJECT_NAME}}"
#      username: "{{os_username}}"
#      password: "{{os_password}}"
#    state: present
#    zone: "{{_r_zone.zone.id}}"
#    name: "{{fqdn}}"
#    recordset_type: "A"
#    region_name: "{{cluster_vars.region}}"
#    records: ["{{ip}}"]
#    ttl: 60
#  delegate_to: localhost
#  run_once: true


##- name: delete all dns
##  shell: openstack recordset delete {{os_zone_id}} {{item.id}}
##  delegate_to: localhost
##  run_once: true
##  with_items: "{{ os_all_dns }}"

#- debug: msg={{os_all_dns}}

#- debug:
#    msg: "{{os_all_dns|json_query(queryvar)}}"
#  vars:
#    queryvar: "[?name=='{{fqdn}}.']"

- name: "Delete hostname/ ip from DNS"
  shell: openstack recordset delete {{os_zone_id}} {{item.id}}
  vars:
    queryvar: "[?name=='{{fqdn}}.']"
  with_items: "{{ os_all_dns|json_query(queryvar) }}"
  when: "ip in item.records or fqdn in item.name"
  become: false
  delegate_to: localhost
  run_once: true

- name: "Create hostname in dns"
  shell: openstack recordset create --records {{ ip }} --type A --ttl 60 {{os_zone_id}} {{ fqdn }}.
  become: false
  delegate_to: localhost
  run_once: true
