---

- name: _add_src_diskinfo_to_cluster_hosts_target/aws | augment cluster_hosts_target auto_volumes with source disk info
  set_fact:
    cluster_hosts_target: |
      {%- for cht_host in cluster_hosts_target -%}
        {%- for cht_autovol in cht_host.auto_volumes -%}
          {%- for chs_host in cluster_hosts_state | selectattr('tagslabels.lifecycle_state', '!=', 'current') -%}
            {%- if cht_host.hostname | regex_replace('-(?!.*-).*') == chs_host.tagslabels.Name | regex_replace('-(?!.*-).*') -%}
              {%- for chs_host_diskinfo in chs_host.disk_info_cloud | selectattr('device_name', '==', cht_autovol.device_name) | selectattr('device_name', '!=', '/dev/sda1') -%}
                {%- set _ = cht_autovol.update({'src': {'instance_id': chs_host.instance_id, 'device_name': chs_host_diskinfo.device_name, 'volume_id': chs_host_diskinfo.ebs.volume_id }}) -%}
              {%- endfor -%}
            {%- endif -%}
          {%- endfor -%}
        {%- endfor -%}
      {%- endfor -%}
      {{cluster_hosts_target}}

- name: _add_src_diskinfo_to_cluster_hosts_target/aws | cluster_hosts_target
  debug: msg={{cluster_hosts_target}}
