---

- name: _add_src_diskinfo_to_cluster_hosts_target/gcp | augment/update cluster_hosts_target auto_volumes with source disk info
  set_fact:
    cluster_hosts_target: |
      {%- for cht_host in cluster_hosts_target -%}
        {%- for cht_autovol in cht_host.auto_volumes -%}
          {%- for chs_host in cluster_hosts_state | json_query('[?tagslabels.lifecycle_state != "current"]') -%}
            {%- if cht_host.hostname | regex_replace('-(?!.*-).*') == chs_host.name | regex_replace('-(?!.*-).*') -%}
              {%- for chs_host_diskinfo in chs_host.disk_info_cloud -%}
                {%- if cht_autovol.initialize_params.disk_name | regex_replace('(.*)-.*(--.*)', '\\1\\2') == chs_host_diskinfo.source | basename | regex_replace('(.*)-.*(--.*)', '\\1\\2') -%}
                  {%- set _ = cht_autovol.update({'device_name': chs_host_diskinfo.source | basename}) -%}
                  {%- set _ = cht_autovol.update({'src': {'hostname': chs_host.name, 'device_name': cht_autovol.device_name, 'source_url': chs_host_diskinfo.source }}) -%}
                  {%- set _ = cht_autovol.update({'initialize_params': {'disk_name': cht_autovol.device_name, 'disk_size_gb': chs_host_diskinfo.diskSizeGb}}) -%}
                {%- endif -%}
              {%- endfor -%}
            {%- endif -%}
          {%- endfor -%}
        {%- endfor -%}
      {%- endfor -%}
      {{cluster_hosts_target}}

- name: _add_src_diskinfo_to_cluster_hosts_target/gcp | cluster_hosts_target
  debug: msg={{cluster_hosts_target}}
