---

- name: Filebeat | Download and install filebeat from elastic.co
  become: yes
  apt:
    deb: "https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{{ filebeat_version }}-amd64.deb"
  register: apt_jobs
  until: apt_jobs is success
  retries: 5
  when: ansible_os_family == 'Debian'

- name: Filebeat | Download and install filebeat from elastic.co
  become: yes
  yum:
    name: "https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{{ filebeat_version }}-x86_64.rpm"
  register: yum_jobs
  until: yum_jobs is success
  retries: 5
  when: ansible_os_family == 'RedHat'

# the variable "beats_target_hosts" will be deprecated in Clusterverse 4.0
- name: Filebeat | Configure filebeat
  block:
    - name: Filebeat | Copy filebeat configuration
      become: yes
      template:
        src: etc/filebeat/filebeat.yml.j2
        dest: "/etc/filebeat/filebeat.yml"
      notify: Filebeat | Restart and enable filebeat

    - name: Filebeat | Copy filebeat service
      become: yes
      template:
        src: lib/systemd/system//filebeat.service.j2
        dest: "/lib/systemd/system/filebeat.service"
      notify: Filebeat | Restart and enable filebeat
  when: (beats_target_hosts is defined and (beats_target_hosts | length)) or (beats_config.filebeat.output_logstash_hosts is defined and (beats_config.filebeat.output_logstash_hosts | length))
