---

- name: Change lifecycle_state label on AWS VM
  ec2_tag:
    aws_access_key: "{{cluster_vars[buildenv].aws_access_key}}"
    aws_secret_key: "{{cluster_vars[buildenv].aws_secret_key}}"
    region: "{{cluster_vars.region}}"
    resource: "{{ item.instance_id }}"
    tags:
      lifecycle_state: "{{new_state}}"
  with_items: "{{ hosts_to_relabel }}"
  when: cluster_vars.type == "aws"


- name: Change lifecycle_state label on GCE VM
  gcp_compute_instance:
    name: "{{item.name}}"
    project: "{{cluster_vars.project_id}}"
    zone: "{{ item.regionzone }}"
    auth_kind: "serviceaccount"
    service_account_file: "{{gcp_credentials_file}}"
    deletion_protection: "{{cluster_vars[buildenv].deletion_protection}}"
    status: "{{item.instance_state}}"
    labels: "{{ item.tagslabels | combine({'lifecycle_state': new_state}) }}"
  with_items: "{{ hosts_to_relabel }}"
  when: cluster_vars.type == "gce"
