---

- name: Delete EC2 instance
  block:
    - name: get existing instance
      ec2_instance_facts:
        filters:
          "tag:Name": "{{host_to_del.hostname}}"
          "instance-state-code": "16"           # Code 16 is 'running' (i.e. not a terminated VM).
        aws_access_key: "{{cluster_vars[clusterid][buildenv].aws_access_key}}"
        aws_secret_key: "{{cluster_vars[clusterid][buildenv].aws_secret_key}}"
        region: "{{cluster_vars[clusterid].region}}"
      register: existing
      delegate_to: localhost

    - set_fact:
        uids_to_del: "{{existing.instances | json_query('[].instance_id[]')}}"

    - name: Remove EC2 instance termination protection
      ec2:
        aws_access_key: "{{cluster_vars[clusterid][buildenv].aws_access_key}}"
        aws_secret_key: "{{cluster_vars[clusterid][buildenv].aws_secret_key}}"
        region: "{{ cluster_vars[clusterid].region }}"
        state: running
        termination_protection: "no"
        instance_ids: "{{ uids_to_del }}"
      when: uids_to_del

    - name: Delete EC2 instance
      ec2:
        aws_access_key: "{{cluster_vars[clusterid][buildenv].aws_access_key}}"
        aws_secret_key: "{{cluster_vars[clusterid][buildenv].aws_secret_key}}"
        region: "{{ cluster_vars[clusterid].region }}"
        state: "absent"
        instance_ids: "{{ uids_to_del }}"
        wait: true
      when: uids_to_del
