---

- name: Delete EC2 instance
  block:
    - name: get existing instance
      ec2_instance_facts:
        filters:
          "tag:Name": "{{host_to_del.hostname}}"
          "tag:release": "{{ release_to_del }}"
          "instance-state-name": ["stopped"]
        aws_access_key: "{{cluster_vars[clusterid][buildenv].aws_access_key}}"
        aws_secret_key: "{{cluster_vars[clusterid][buildenv].aws_secret_key}}"
        region: "{{cluster_vars[clusterid].region}}"
      register: existing
      delegate_to: localhost
      run_once: true

    - name: Remove EC2 instance termination protection
      ec2:
        aws_access_key: "{{cluster_vars[clusterid][buildenv].aws_access_key}}"
        aws_secret_key: "{{cluster_vars[clusterid][buildenv].aws_secret_key}}"
        region: "{{ cluster_vars[clusterid].region }}"
        state: "stopped"
        termination_protection: "no"
        instance_ids: ["{{ existing.instances[0].instance_id }}"]
      when: (existing.instances is defined) and (existing.instances | length>0) and (existing.instances[0].instance_id is defined)
      delegate_to: localhost
      run_once: true

    - name: set maintenance_mode to true
      ec2_tag:
        aws_access_key: "{{cluster_vars[clusterid][buildenv].aws_access_key}}"
        aws_secret_key: "{{cluster_vars[clusterid][buildenv].aws_secret_key}}"
        region: "{{cluster_vars[clusterid].region}}"
        resource: "{{ existing.instances[0].instance_id }}"
        tags:
          maintenance_mode: "true"
      delegate_to: localhost
      run_once: true
      when: (existing.instances is defined) and (existing.instances | length>0) and (existing.instances[0].instance_id is defined)

    - name: Delete EC2 instance
      ec2:
        aws_access_key: "{{cluster_vars[clusterid][buildenv].aws_access_key}}"
        aws_secret_key: "{{cluster_vars[clusterid][buildenv].aws_secret_key}}"
        region: "{{ cluster_vars[clusterid].region }}"
        state: "absent"
        instance_ids: ["{{ existing.instances[0].instance_id }}"]
        wait: true
      when: (existing.instances is defined) and (existing.instances | length>0) and (existing.instances[0].instance_id is defined)
      delegate_to: localhost
      run_once: true