---

- debug: msg="Stop {{host_to_stop.hostname}}, release {{release_to_stop}}"

- name: aws_stop | Stop EC2 instance
  block:
    - name: get existing instance
      ec2_instance_facts:
        filters:
          "tag:Name": "{{ host_to_stop.hostname }}"
          "tag:release": "{{ release_to_stop }}"
          "tag:deploy_status": "{{ deploy_status_to_stop }}"
          "instance-state-name": ["running", "stopped"]
        aws_access_key: "{{cluster_vars[clusterid][buildenv].aws_access_key}}"
        aws_secret_key: "{{cluster_vars[clusterid][buildenv].aws_secret_key}}"
        region: "{{cluster_vars[clusterid].region}}"
      register: existing
      delegate_to: localhost
      run_once: true

    - name: aws_stop | Stop EC2 instance
      ec2:
        aws_access_key: "{{cluster_vars[clusterid][buildenv].aws_access_key}}"
        aws_secret_key: "{{cluster_vars[clusterid][buildenv].aws_secret_key}}"
        region: "{{ cluster_vars[clusterid].region }}"
        state: "stopped"
        instance_ids: ["{{ existing.instances[0].instance_id }}"]
        wait: true
      when: (existing.instances is defined) and (existing.instances | length>0) and (existing.instances[0].instance_id is defined)
      delegate_to: localhost
      run_once: true