---

- debug: msg="Deleting and recreating {{host_to_del.hostname}}"

- include_tasks: gce.yml
  when: cluster_vars[clusterid].type == "gce"

- include_tasks: aws.yml
  when: cluster_vars[clusterid].type == "aws"

- name: get argument variables
  get_argv:

- name: "set argument variables for {{mainclusteryml}}"
  set_fact:
    maincluster_yml_args: "{{ (argv | join(' ')) | regex_replace('redeploy.yml', mainclusteryml) }}"

- name: "run {{mainclusteryml}}"
  shell: "{{maincluster_yml_args}}"
  register: r_mainclusteryml

- debug: msg={{r_mainclusteryml}}