---

- name: clean/networking/aws | Delete AWS security group
  ec2_group:
    name: "{{ cluster_name }}-sg"
    region: "{{cluster_vars.region}}"
    vpc_id: "{{vpc_id}}"
    aws_access_key: "{{cluster_vars[buildenv].aws_access_key}}"
    aws_secret_key: "{{cluster_vars[buildenv].aws_secret_key}}"
    state: absent
  when: cluster_vars.type == "aws"

- block:
    - name: clean/networking/gcp | Delete GCP cluster firewalls
      gcp_compute_firewall:
        name: "{{ item.name }}"
        state: "absent"
        auth_kind: "serviceaccount"
        service_account_file: "{{gcp_credentials_file}}"
        project: "{{cluster_vars[buildenv].vpc_network_project}}"
      with_items: "{{ cluster_vars.firewall_rules }}"

    - name: clean/networking/gcp | Delete the GCP network (if -e create_gcp_network=true)
      gcp_compute_network:
        name: "{{cluster_vars[buildenv].vpc_network_name}}"
        auth_kind: "serviceaccount"
        service_account_file: "{{gcp_credentials_file}}"
        project: "{{cluster_vars.project_id}}"
        state: absent
      when: create_gcp_network is defined and create_gcp_network|bool
  when: cluster_vars.type == "gcp"
