---

- debug: msg="{{hosts_to_clean}}"

- block:
    - name: clean/del_vms | Remove EC2 instances termination protection
      ec2:
        aws_access_key: "{{cluster_vars[buildenv].aws_access_key}}"
        aws_secret_key: "{{cluster_vars[buildenv].aws_secret_key}}"
        region: "{{ cluster_vars.region }}"
        state: "{{ item.instance_state }}"
        termination_protection: "no"
        instance_ids: ["{{ item.instance_id }}"]
      with_items: "{{ hosts_to_clean | json_query(\"[].{instance_id:instance_id, instance_state: instance_state}\") }}"

    - name: clean/del_vms | Delete EC2 instances
      ec2:
        aws_access_key: "{{cluster_vars[buildenv].aws_access_key}}"
        aws_secret_key: "{{cluster_vars[buildenv].aws_secret_key}}"
        region: "{{ cluster_vars.region }}"
        state: "absent"
        instance_ids: "{{ hosts_to_clean | json_query(\"[].instance_id\") }}"
        wait: true
      delegate_to: localhost
      run_once: true
  when: cluster_vars.type == "aws"

- block:
    - name: Remove deletion protection
      command: "gcloud compute instances update {{item.name}} --no-deletion-protection --zone {{ item.regionzone }}"
      when: cluster_vars[buildenv].deletion_protection | bool
      with_items: "{{ hosts_to_clean }}"

#    - name: Remove deletion protection (broken until https://github.com/ansible-collections/ansible_collections_google/pull/163 gets into a release)
#      gcp_compute_instance:
#        name: "{{item.name}}"
#        project: "{{cluster_vars.project_id}}"
#        zone: "{{ item.regionzone }}"
#        auth_kind: "serviceaccount"
#        service_account_file: "{{gcp_credentials_file}}"
#        deletion_protection: 'no'
#      with_items: "{{ hosts_to_clean }}"

    - debug: msg="{{hosts_to_clean}}"

    - name: Delete GCE VM
      gcp_compute_instance:
        name: "{{item.name}}"
        project: "{{cluster_vars.project_id}}"
        zone: "{{ item.regionzone }}"
        auth_kind: "serviceaccount"
        service_account_file: "{{gcp_credentials_file}}"
        state: "absent"
      with_items: "{{ hosts_to_clean }}"
      register: r__gcp_compute_instance
      async: 7200
      poll: 0

    - name: Wait for gce instance deletion to complete
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: async_jobs
      until: async_jobs.finished
      retries: 300
      with_items: "{{r__gcp_compute_instance.results}}"
  when: cluster_vars.type == "gce"
