---

- include_tasks: aws.yml
  when: cluster_vars.type == "aws"

- include_tasks: gce.yml
  when: cluster_vars.type == "gce"

- include_tasks: dns.yml
  when: (cluster_vars.dns_server is defined and cluster_vars.dns_server != "")  and  (cluster_vars.dns_zone_external is defined and cluster_vars.dns_zone_external != "")

- name: Delete the inventory file
  block:
    - stat: path={{inventory_file}}
      register: stat_inventory_file
      when: inventory_file is defined

    - set_fact:
        new_inventory_file: "{{ inventory_file if (((stat_inventory_file.stat is defined and stat_inventory_file.stat.exists) or (stat_inventory_file.skipped is defined and stat_inventory_file.skipped)) and inventory_dir is defined and inventory_dir==playbook_dir) else playbook_dir + '/inventory_' + cluster_name }}"

    # Check the inventory_dir==playbook_dir, because the default inventory is /etc/ansible/hosts
    - name: Delete the inventory file
      file:
        path: "{{new_inventory_file}}"
        state: absent

    - name: Refresh inventory
      meta: refresh_inventory
