---

- debug: msg="{{cluster_hosts_state}}"

- name: clean | Delete the inventory file
  block:
    - name: clean | Delete VMs
      include_tasks: clean_vms.yml

    - name: clean | Delete Networking
      include_tasks: clean_networking.yml

    - name: clean | Delete DNS
      include_tasks: clean_dns.yml
      when: (cluster_vars.dns_server is defined and cluster_vars.dns_server != "") and (cluster_vars.dns_zone_external is defined and cluster_vars.dns_zone_external != "")
  vars:
    hosts_to_clean: |
      {%- if clean == '_all_' -%}
      {{ cluster_hosts_state | json_query('[]') }}
      {%- else -%}
      {{ cluster_hosts_state | json_query('[?tagslabels.lifecycle_state==`' + clean + '`]') }}
      {%- endif -%}


- name: clean | Delete the inventory file
  block:
    - stat: path={{inventory_file}}
      register: stat_inventory_file
      when: inventory_file is defined

    - set_fact:
        new_inventory_file: "{{ inventory_file if (((stat_inventory_file.stat is defined and stat_inventory_file.stat.exists) or (stat_inventory_file.skipped is defined and stat_inventory_file.skipped)) and inventory_dir is defined and inventory_dir==playbook_dir) else playbook_dir + '/inventory_' + cluster_name }}"

    # Check the inventory_dir==playbook_dir, because the default inventory is /etc/ansible/hosts
    - name: Delete the inventory file
      file:
        path: "{{new_inventory_file}}"
        state: absent

    - name: Refresh inventory
      meta: refresh_inventory
