---

- name: Create vmware instances
  vsphere_guest:
    vcenter_hostname: "{{ vcenter_server }}"
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    guest: "{{ item.hostname }}"
    from_template: yes
    template_src: "{{ template_name }}"
    cluster: "{{ siteconfig[site_name][application_environment]['vcenter_cluster'] }}"
    resource_pool: "/Resources/{{ resource_pool }}"
    vm_nic:
      nic1:
        type: vmxnet3
        network: "{{ siteconfig[site_name][application_environment]['vcenter_vlan_1'][network_type][network] }}"
        network_type: "{{ network_type }}"
    vmware_guest_facts: no
    vm_extra_config:
      notes: "{{item.hosttype}}"
  register: new_instances
  run_once: true
  with_items: "{{cluster_hosts_flat}}"
