
- debug: msg="Removing {{host_to_del}}"

- name: Change lifecycle_state label from 'current' to 'retiring'
  include_role:
    name: clusterverse/redeploy/__common
    tasks_from: "set_lifecycle_state_label_{{cluster_vars.type}}.yml"
  vars:
    hosts_to_relabel: "{{ [host_to_del] }}"
    new_state: "retiring"

- name: by_hosttype_by_host | run predeleterole role
  include_role:
    name: "{{predeleterole}}"
  vars:
    hosts_to_remove: "{{ [host_to_del] }}"
  when: predeleterole is defined and predeleterole != ""

- name: by_hosttype_by_host | Power off old VM
  include_role:
    name: clusterverse/redeploy/__common
    tasks_from: "powerchange_vms_{{cluster_vars.type}}.yml"
  vars:
    hosts_to_powerchange: "{{ [host_to_del] }}"
    powerchange_new_state: "stop"

- name: "Run {{mainclusteryml}} to fix cluster"
  shell: "{{ (argv | join(' ')) | regex_replace('redeploy.yml', mainclusteryml) }} {{ redeploy_extra_vars | extravars_from_dict }}"
  register: r__mainclusteryml
  no_log: True
  ignore_errors: yes
- debug: msg="{{[r__mainclusteryml.stdout_lines] + [r__mainclusteryml.stderr_lines]}}"
  failed_when: r__mainclusteryml is failed
  when: r__mainclusteryml is failed  or  (debug_nested_log_output is defined and debug_nested_log_output|bool)

- name: re-acquire the dynamic inventory
  include_role:
    name: clusterverse/dynamic_inventory
